export const ADDTOCART  = "ADDTOCART"
export const SEARCH = "SEARCH"
export const FILTER  = "FILTER"
export const GET_DATA = "GET_DATA"
export const GET_ITEMS = "GET_ITEMS"
export const DELETE_ITEM = "DELETE_ITEM"